import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Single source of truth: .pi/system/{persona,core,router,delegation,tools,guardrails}.md
// Output (skill-native): .pi/SYSTEM.md — Pi replaces the default system
// prompt with it for this project. Never edit SYSTEM.md by hand.
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sys = join(root, ".pi", "system");
const PARTS = ["persona.md", "core.md", "router.md", "delegation.md", "tools.md", "guardrails.md"];

const out = [
  "<!-- GENERATED by scripts/assemble-system.mjs — edit .pi/system/*.md, then re-run. -->",
  "# deu-pi-agent v0.1.0 — project system prompt (deu)",
  ...PARTS.map((f) => `<!-- deu:${f} -->\n${readFileSync(join(sys, f), "utf8").trim()}`),
].join("\n\n---\n\n") + "\n";

writeFileSync(join(root, ".pi", "SYSTEM.md"), out);
console.log("OK: .pi/SYSTEM.md assembled from " + PARTS.join(", "));
